logging:
  level:
    org:
      springframework:
        test:
          context:
            cache: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:tc:postgresql://localhost:5432/test?TC_INITSCRIPT=testcases/postgres/create.sql
    username: sa
    password: password

payroll:
  uri: http://localhost:8089/payroll


