gatling {
  socket {
    soKeepAlive = true                    # if TCP keepalive configured at OS level should be used
  }
  ssl {
    useOpenSsl = true                    # if OpenSSL should be used instead of JSSE (only the latter can be debugged with -Djavax.net.debug=ssl)
  }
}